### ISSUE TITLE
Lack of pull-up resistor

### ISSUE THREAD

**Issue by chewdonovan** [edwardsnjd/pi-door-sensor#1]
:confused: 
DNLGTM :-1: 
Todo:
- [ ] add pull-up resistor
- [x] read https://en.wikipedia.org/wiki/Pull-up_resistor

**Comment by edwardsnjd** [comment]
@chewdonovan Thanks for the tip!

Luckily the Python library has this covered for noobs like me:
https://gpiozero.readthedocs.io/en/stable/api_input.html#button
